name: Cypress CI/CD

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pramudya Testing
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/Pramudya/*

      - name: Risang Testing
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/Risang/*

      - name: Tasya Testing
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/Tasya/*
          
      - name: Zulfan Testing
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/Zulfan/*
